Hw3
Maksym-Zyza/nodejs-rest-api pull request #2
Opened 2021-05-15 11:11 UTC by Maksym-Zyza

Прохання перевірити Дз3

2021-05-15 18:29 UTC, SergeiKBB requested changes

2021-05-15 18:29 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://mz:ziza357571@cluster0.rkvtf.mongodb.net/db-contacts?retryWrites=true&w=majority
этот файл должен быть в гитигноре

2021-05-15 19:56 UTC, Maksym-Zyza commented on .env
> +URI_DB=mongodb+srv://mz:ziza357571@cluster0.rkvtf.mongodb.net/db-contacts?retryWrites=true&w=majority
Ок, дякую!) видалив файл на git та додай його в gitignore

2021-05-16 19:47 UTC, SergeiKBB approved these changes

2021-05-17 06:56 UTC, merged